BINS=main.elf

OBJS= lib/uart.o lib/port.o lib/motor.o lib/joystick.o lib/encoder.o lib/eeprom_manager.o
HEADERS= lib/uart.h ../avr_client_common/packets.h lib/port.h lib/joystick.h lib/motor.h lib/encoder.h lib/eeprom_manager.h
CROSS_PLATFROM = ../avr_client_common/serial_protocol.*

include avr_common/avr.mk
